let productsDB = [{
    id: 0,
    title: "Dress",
    category: "women",
    desc: "lhjh hjh gfhy fyu tyu ",
    price: 50,
    imgURL: "images/women-dresses1.jpg",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "pink"],
    qty: 0,
    chosenSize: 's',
    chosenColor: 'green'
  },
  {
    id: 1,
    title: "T-Shirt",
    category: "women",
    desc: "Slogan Print BCI Cotton T-shirt with Round Neck and Short Sleeves",
    price: 150,
    imgURL: "images/women2.jpg",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "pink"],
    qty: 0,
    chosenSize: 's',
    chosenColor: 'green'
  },
  {
    id: 2,
    title: "Skirt",
    category: "women",
    desc: "Floral Print Midi Skirt with Ruffle Detai",
    price: 170,
    imgURL: "images/women3.jpg",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "pink"],
    qty: 0,
    chosenSize: 's',

    chosenColor: 'green'

  },
  {
    id: 3,
    title: "Shirt",
    category: "men",
    desc: "Textured T-shirt with Cowl Neck and Short Sleeves",
    price: 210,
    imgURL: "images/men1.jpg",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "pink"],
    qty: 0,
    chosenSize: 's',
    chosenColor: 'green'
  },
  {
    id: 4,
    title: "Shirt",
    category: "men",
    desc: "All-Over Printed Polo T-shirt with Mandarin Collar and Short Sleeves",
    price: 280,
    imgURL: "images/men2.jpg",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "pink"],
    qty: 0,
    chosenSize: 's',
    chosenColor: 'green'
  },
  {
    id: 5,
    title: "Jeans",
    category: "men",
    desc: "Ripped Mid-Rise Denim Jeans with Button Closure and Pockets",
    price: 190,
    imgURL: "images/men3.jpg",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "pink"],
    qty: 0,
    chosenSize: 's',
    chosenColor: 'green'
  },
  {
    id: 6,
    title: "shirt",
    category: "kids",
    desc: "Ripped Mid-Rise Denim Jeans with Button Closure and Pockets",
    price: 190,
    imgURL: "images/kids1.jpg",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "pink"],
    qty: 0,
    chosenSize: 's',
    chosenColor: 'green'
  },
  {
    id: 7,
    title: "jacket",
    category: "kids",
    desc: "Ripped Mid-Rise Denim Jeans with Button Closure and Pockets",
    price: 280,
    imgURL: "images/kids2.jpg",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "pink"],
    qty: 0,
    chosenSize: 's',
    chosenColor: 'green'
  },
  {
    id: 8,
    title: "jacket",
    category: "kids",
    desc: "Ripped Mid-Rise Denim Jeans with Button Closure and Pockets",
    price: 320,
    imgURL: "images/kids3.jpg",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "pink"],
    qty: 0,
    chosenSize: 's',
    chosenColor: 'green'
  },
  {
    id: 9,
    title: "jogger",
    category: "men",
    desc: "Ripped Mid-Rise Denim Jeans with Button Closure and Pockets",
    price: 190,
    imgURL: "images/men4.jpg",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "pink"],
    qty: 0,
    chosenSize: 's',
    chosenColor: 'green'
  },
  {
    id: 10,
    title: "short",
    category: "men",
    desc: "Ripped Mid-Rise Denim Jeans with Button Closure and Pockets",
    price: 160,
    imgURL: "images/men5.jpg",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "pink"],
    qty: 0,
    chosenSize: 's',
    chosenColor: 'green'
  },
  {
    id: 11,
    title: "shirt",
    category: "men",
    desc: "Ripped Mid-Rise Denim Jeans with Button Closure and Pockets",
    price: 100,
    imgURL: "images/men6.jpg",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "pink"],
    qty: 0,
    chosenSize: 's',
    chosenColor: 'green'
  },
];